package com.stg.entity;

public enum StateOfRegistration {
	
	ANDAMAN_AND_NICOBAR__AN,
	ANDHRA_PRADESH__AP,
	ARUNACHAL_PRADESH__AR,
	ASSAM__AS,
	BIHAR__BR,
	CHANDIGARH__CH,
	DADRA_AND_NAGAR_HAVELI__DN,
	DAMAN_AND_DIU__DD,
	DELHI__DL,
	GOA__GA,
	GUJARAT__GJ,
	HARYANA__HR,
	HIMACHAL_PRADESH__HP,
	JAMMU_AND_KASHMIR__JK,
	KARNATAKA__KA,
	KERALA__KL,
	LAKSHADWEEP__LD,
	MADHYA_PRADESH__MP,
	MAHARASHTRA__MH,
	MANIPUR__MN,
	MEGHALAYA__ML,
	MIZORAM__MZ,
	NAGALAND__NL,
	ORISSA__OR,
	PONDICHERRY__PY,
	PUNJAB__PN,
	RAJASTHAN__RJ,
	SIKKIM__SK,
	TAMILNADU__TN,
	TRIPURA__TR,
	UTTAR_PRADESH__UP,
	WEST_BENGAL__WB





}
